# Generated by Django 4.1.5 on 2023-01-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(choices=[('ES', 'Espania'), ('IT', 'Italia'), ('FR', 'Francesa')], max_length=2)),
            ],
        ),
    ]
